# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' helper to convert std::string to tree
#'
#' @description inner work horse for rcpp_create_tree
#' @inheritParams text_ref
#' @inheritParams singular_operators_ref
#' @inheritParams binary_operators_ref
#' @inheritParams valid_functions_ref
#' @return a Rcpp::List
#' @noRd
NULL

#' rcpp_find_parenthesis
#'
#' @description See R function find_parenthesis
#' @inheritParams text_ref
#' @return a std::string
#' @noRd
rcpp_find_parenthesis <- function(text) {
    .Call(`_evalR_rcpp_find_parenthesis`, text)
}

#' Convert a statement into an evaluation tree
#'
#' @description See create_tree R function
#' @inheritParams text_ref
#' @inheritParams singular_operators_ref
#' @inheritParams binary_operators_ref
#' @inheritParams valid_functions_ref
#' @return a Rcpp::List
#' @noRd
rcpp_create_tree <- function(text, singular_operators, binary_operators, valid_functions) {
    .Call(`_evalR_rcpp_create_tree`, text, singular_operators, binary_operators, valid_functions)
}

